# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: FirstJob
      steps:
        - bash: echo Build FirstJob  
    - job: SeconJob
      steps:
        - bash: echo Build SecondJob
      
- stage: Dev
  jobs:
    - job: DeveopmentJob
      steps:
        - bash: echo Deployment  FirstJob
- stage: Staging
  jobs:
    - job: Stagingjob
      steps:
        - bash: echo Staging  FirstJob
- stage: Production
  jobs:
    - job: ProductionJob
      steps:
        - bash: echo Production  FirstJob   

