trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: FirstJob
      steps:
        - bash: echo Build FirstJob  
        - bash: echo $(PipelineLevelVariable)
    - job: SeconJob
      steps:
        - bash: echo Build SecondJob
      
- stage: Dev
  variables:
    environment : DevelopMent
  dependsOn: Build
  jobs:
    - job: DeveopmentJob
      steps:
        - bash: echo Deployment  FirstJob
        - bash: echo $(environment)Deployjob
- stage: Testing
  variables:
    environment : QA
  jobs:
    - job: TestingJob
      steps:
        - bash: echo $(environment)QAjob
 
- stage: Staging
  dependsOn: Dev
  jobs:
    - job: Stagingjob
      steps:
        - bash: echo Staging  FirstJob
- stage: Production
  jobs:
    - job: ProductionJob
      steps:
        - bash: echo Production  FirstJob   

