# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: FirstJob
      steps:
        - bash: echo Build FirstJob
        - bash: echo $(PipelineLevelVariable)
        - bash: echo $(Build.BuildId)   
        - bash: echo $(Build.BuildNumber) 
        - bash: echo $(Build.BuildUri) 
        - bash: echo $(Build.ContainerId) 
        - bash: echo $(Build.DefinitionName) 
        - bash: echo $(Sytem.DefaultWorkingDirectory) 
        - bash: ls -R $(Sytem.DefaultWorkingDirectory) 
        - bash: echo $(Build.ArtifactStagingDirectory) 
        - bash: java -version
        - bash: python --version
        - bash: node --version
        - bash: mvn -version
        - bash: ls -R $(Build.ArtifactStagingDirectory) 
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Sytem.DefaultWorkingDirectory)'
            Contents: |
              **/*.yaml
              **/*.tf
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - bash: ls -R $(Build.ArtifactStagingDirectory) 


