#build the image
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
#Stage 1
#Build the docker image
#Publish the Artifact
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'lokanarayan-docker-hub'
        repository: 'lokanarayana/hello-world-java'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
# publish the K8 files and create the Artifates and availabe in pipeline
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manfiest'
        publishLocation: 'Container'
# stage 1 is compleated we have build the docker images and we are ready to publish the k8 file

# stage 2 downloading file into the artifacts directory
# 2 Get k8 files
# 3 Deploye to k8 cluster  with docker image
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manfiest'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'

#Run the K8 
# deploy k8

    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'Azure-K8-Connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml' # deployment .yam file to execute
        containers: 'lokanarayana/hello-world-java:$(tage)' #tage is buidid 